FROM node:11.1
ENV PORT_HTTP 3000
ENV PORT_HTTPS 8443
ENV dist .
WORKDIR /usr/src/app
COPY ["./*.js", "./*.json", "./"]
COPY src src
RUN npm i --silent && npm run build && rm -rf node_modules *.json src *.js && mv dist/* . && rmdir dist
RUN ls -R | grep ":$" | sed -e 's/:$//' -e 's/[^-][^\/]*\//--/g' -e 's/^/   /' -e 's/-/|/'
EXPOSE 3000 8443
CMD node server.js